# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import users_pb2 as users__pb2


class UsersStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Register = channel.unary_unary(
        '/users.Users/Register',
        request_serializer=users__pb2.ResgisterLoginRequest.SerializeToString,
        response_deserializer=users__pb2.UserDataResponse.FromString,
        )
    self.Login = channel.unary_unary(
        '/users.Users/Login',
        request_serializer=users__pb2.ResgisterLoginRequest.SerializeToString,
        response_deserializer=users__pb2.UserDataResponse.FromString,
        )
    self.GetUserInfo = channel.unary_unary(
        '/users.Users/GetUserInfo',
        request_serializer=users__pb2.GetUserInfoRequest.SerializeToString,
        response_deserializer=users__pb2.UserDataResponse.FromString,
        )


class UsersServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Register(self, request, context):
    """注册
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Login(self, request, context):
    """登陆
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUserInfo(self, request, context):
    """查询
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UsersServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Register': grpc.unary_unary_rpc_method_handler(
          servicer.Register,
          request_deserializer=users__pb2.ResgisterLoginRequest.FromString,
          response_serializer=users__pb2.UserDataResponse.SerializeToString,
      ),
      'Login': grpc.unary_unary_rpc_method_handler(
          servicer.Login,
          request_deserializer=users__pb2.ResgisterLoginRequest.FromString,
          response_serializer=users__pb2.UserDataResponse.SerializeToString,
      ),
      'GetUserInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserInfo,
          request_deserializer=users__pb2.GetUserInfoRequest.FromString,
          response_serializer=users__pb2.UserDataResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'users.Users', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
