# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='users.proto',
  package='users',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0busers.proto\x12\x05users\"O\n\x15ResgisterLoginRequest\x12\x12\n\nlogin_type\x18\x01 \x01(\x03\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"\xf8\x01\n\x10UserDataResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x1c\n\x04hint\x18\x02 \x01(\x0e\x32\x0e.users.ResHint\x12\x0f\n\x07user_id\x18\x03 \x01(\x03\x12\x12\n\nlogin_type\x18\x04 \x01(\x03\x12\x10\n\x08username\x18\x05 \x01(\t\x12\r\n\x05\x65mail\x18\x06 \x01(\t\x12\r\n\x05phone\x18\x07 \x01(\t\x12\x12\n\nfirst_name\x18\x08 \x01(\t\x12\x11\n\tlast_name\x18\t \x01(\t\x12\x12\n\nlast_login\x18\n \x01(\t\x12\x13\n\x0b\x64\x61te_joined\x18\x0b \x01(\t\x12\x10\n\x08\x66ullname\x18\x0c \x01(\t\"%\n\x12GetUserInfoRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03*\x82\x01\n\x07ResHint\x12\x12\n\x0eUSERNAME_EXIST\x10\x00\x12\x11\n\rINVALID_PHONE\x10\x01\x12\x1e\n\x1aWRONG_USERNAME_OR_PASSWORD\x10\x02\x12\x10\n\x0cNO_THIS_USER\x10\x03\x12\x0b\n\x07UNMATCH\x10\x04\x12\x11\n\rWRONG_CAPTCHA\x10\x05\x32\xd3\x01\n\x05Users\x12\x43\n\x08Register\x12\x1c.users.ResgisterLoginRequest\x1a\x17.users.UserDataResponse\"\x00\x12@\n\x05Login\x12\x1c.users.ResgisterLoginRequest\x1a\x17.users.UserDataResponse\"\x00\x12\x43\n\x0bGetUserInfo\x12\x19.users.GetUserInfoRequest\x1a\x17.users.UserDataResponse\"\x00\x62\x06proto3')
)

_RESHINT = _descriptor.EnumDescriptor(
  name='ResHint',
  full_name='users.ResHint',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='USERNAME_EXIST', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_PHONE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WRONG_USERNAME_OR_PASSWORD', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NO_THIS_USER', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNMATCH', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WRONG_CAPTCHA', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=394,
  serialized_end=524,
)
_sym_db.RegisterEnumDescriptor(_RESHINT)

ResHint = enum_type_wrapper.EnumTypeWrapper(_RESHINT)
USERNAME_EXIST = 0
INVALID_PHONE = 1
WRONG_USERNAME_OR_PASSWORD = 2
NO_THIS_USER = 3
UNMATCH = 4
WRONG_CAPTCHA = 5



_RESGISTERLOGINREQUEST = _descriptor.Descriptor(
  name='ResgisterLoginRequest',
  full_name='users.ResgisterLoginRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='login_type', full_name='users.ResgisterLoginRequest.login_type', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='users.ResgisterLoginRequest.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='users.ResgisterLoginRequest.password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=101,
)


_USERDATARESPONSE = _descriptor.Descriptor(
  name='UserDataResponse',
  full_name='users.UserDataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='users.UserDataResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hint', full_name='users.UserDataResponse.hint', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='users.UserDataResponse.user_id', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='login_type', full_name='users.UserDataResponse.login_type', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='users.UserDataResponse.username', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='users.UserDataResponse.email', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='phone', full_name='users.UserDataResponse.phone', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='first_name', full_name='users.UserDataResponse.first_name', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='users.UserDataResponse.last_name', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_login', full_name='users.UserDataResponse.last_login', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date_joined', full_name='users.UserDataResponse.date_joined', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fullname', full_name='users.UserDataResponse.fullname', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=352,
)


_GETUSERINFOREQUEST = _descriptor.Descriptor(
  name='GetUserInfoRequest',
  full_name='users.GetUserInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='users.GetUserInfoRequest.user_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=354,
  serialized_end=391,
)

_USERDATARESPONSE.fields_by_name['hint'].enum_type = _RESHINT
DESCRIPTOR.message_types_by_name['ResgisterLoginRequest'] = _RESGISTERLOGINREQUEST
DESCRIPTOR.message_types_by_name['UserDataResponse'] = _USERDATARESPONSE
DESCRIPTOR.message_types_by_name['GetUserInfoRequest'] = _GETUSERINFOREQUEST
DESCRIPTOR.enum_types_by_name['ResHint'] = _RESHINT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ResgisterLoginRequest = _reflection.GeneratedProtocolMessageType('ResgisterLoginRequest', (_message.Message,), dict(
  DESCRIPTOR = _RESGISTERLOGINREQUEST,
  __module__ = 'users_pb2'
  # @@protoc_insertion_point(class_scope:users.ResgisterLoginRequest)
  ))
_sym_db.RegisterMessage(ResgisterLoginRequest)

UserDataResponse = _reflection.GeneratedProtocolMessageType('UserDataResponse', (_message.Message,), dict(
  DESCRIPTOR = _USERDATARESPONSE,
  __module__ = 'users_pb2'
  # @@protoc_insertion_point(class_scope:users.UserDataResponse)
  ))
_sym_db.RegisterMessage(UserDataResponse)

GetUserInfoRequest = _reflection.GeneratedProtocolMessageType('GetUserInfoRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETUSERINFOREQUEST,
  __module__ = 'users_pb2'
  # @@protoc_insertion_point(class_scope:users.GetUserInfoRequest)
  ))
_sym_db.RegisterMessage(GetUserInfoRequest)



_USERS = _descriptor.ServiceDescriptor(
  name='Users',
  full_name='users.Users',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=527,
  serialized_end=738,
  methods=[
  _descriptor.MethodDescriptor(
    name='Register',
    full_name='users.Users.Register',
    index=0,
    containing_service=None,
    input_type=_RESGISTERLOGINREQUEST,
    output_type=_USERDATARESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Login',
    full_name='users.Users.Login',
    index=1,
    containing_service=None,
    input_type=_RESGISTERLOGINREQUEST,
    output_type=_USERDATARESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetUserInfo',
    full_name='users.Users.GetUserInfo',
    index=2,
    containing_service=None,
    input_type=_GETUSERINFOREQUEST,
    output_type=_USERDATARESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERS)

DESCRIPTOR.services_by_name['Users'] = _USERS

# @@protoc_insertion_point(module_scope)
