# Generated by Django 2.0 on 2017-12-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='address',
            field=models.URLField(blank=True),
        ),
    ]
