# Generated by Django 2.0 on 2017-12-13 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_favorite_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favorite',
            name='address',
            field=models.URLField(max_length=100),
        ),
    ]
