# Generated by Django 2.0 on 2017-12-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_auto_20171213_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
