# Generated by Django 2.0 on 2017-12-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_auto_20171216_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='address',
            field=models.TextField(),
        ),
    ]
