# Generated by Django 2.0 on 2017-12-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0005_auto_20171217_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='address',
            field=models.URLField(),
        ),
    ]
