# Generated by Django 2.0 on 2017-12-21 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guide', '0006_auto_20171217_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='owner',
            field=models.OneToOneField(default='pencil', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner of the favorite site'),
        ),
    ]
