# Generated by Django 2.0 on 2018-01-03 13:50

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=blog.models.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=50)),
                ('blog_writer', models.CharField(max_length=30)),
                ('blog_describe', models.TextField()),
            ],
        ),
    ]
