# Generated by Django 2.0 on 2017-12-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogpost',
            new_name='Blog_post',
        ),
    ]
