# Generated by Django 2.0 on 2017-12-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171205_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=50)),
                ('blog_writer', models.CharField(max_length=30)),
                ('blog_describe', models.TextField()),
            ],
        ),
    ]
