# Generated by Django 2.0 on 2018-01-04 08:10

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180103_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=blog.models.upload_to)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='image',
        ),
        migrations.AddField(
            model_name='post_image',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog_post', verbose_name='the image in the post'),
        ),
    ]
